const COLORS = {
  BACKGROUND_COLOR: '#ffffff',
  TEXT_COLOR: '#0c0a1d',
  SECONDARY_TEXT_COLOR: '#ffffff',
  THIRD_RATE_TEXT_COLOR: '#5AF2B5',
  PRIMARY_ITEM_COLOR: '#4c35af',
  SECONDARY_ITEM_COLOR: '#161425',
  HOVER_LIGHT_COLOR: '#e3bebe',
} as const;

const DARK_THEME_COLORS = {
  BACKGROUND_COLOR: '#0c0a1d',
  TEXT_COLOR: '#ffffff',
  PRIMARY_ITEM_COLOR: '#4c35af',
  SECONDARY_TEXT_COLOR: '#ffffff',
  THIRD_RATE_TEXT_COLOR: '#ffffff',
  SECONDARY_ITEM_COLOR: '#161425',
  HOVER_LIGHT_COLOR: '#e3bebe',
} as const;

export { COLORS, DARK_THEME_COLORS };
