const COLORS = {
  BACKGROUND_COLOR: '#ffffff',
  TEXT_COLOR: '#0c0a1d',
  SECONDARY_TEXT_COLOR: '#ffffff',
  PRIMARY_ITEM_COLOR: '#4c35af',
  SECONDARY_ITEM_COLOR: '#161425',
};

const DARK_THEME_COLORS = {
  BACKGROUND_COLOR: '#0c0a1d',
  TEXT_COLOR: '#ffffff',
  PRIMARY_ITEM_COLOR: '#4c35af',
  SECONDARY_ITEM_COLOR: '#161425',
  SECONDARY_TEXT_COLOR: '#ffffff',
};

export { COLORS, DARK_THEME_COLORS };
